language: node_js
notifications: 
  webhooks: https://oapi.dingtalk.com/robot/send?access_token=4a02b07e4d14c0b72e7e7991158b87c3c229ef228bdb80f60d68140ea6b35607
node_js:
  - lts/*
script:
  - bash deploy.sh
# deploy:
#   provider: pages
#   skip_cleanup: true
#   local_dir: docs/.vuepress/dist
#   github_token: $GH_TOKEN # 在 GitHub 中生成，用于允许 Travis 向你的仓库推送代码。在 Travis 的项目设置页面进行配置，设置为 secure variable
#   keep_history: true
#   on:
#     branch: master
